//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLCourse {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLCourse.Course[] prerequisite_listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int unitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLCourse.Course[] prerequisite_list {
            get {
                return this.prerequisite_listField;
            }
            set {
                if ((object.ReferenceEquals(this.prerequisite_listField, value) != true)) {
                    this.prerequisite_listField = value;
                    this.RaisePropertyChanged("prerequisite_list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                if ((this.unitsField.Equals(value) != true)) {
                    this.unitsField = value;
                    this.RaisePropertyChanged("units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLCourse.ISLCourse")]
    public interface ISLCourse {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourseList", ReplyAction="http://tempuri.org/ISLCourse/GetCourseListResponse")]
        web136.SLCourse.GetCourseListResponse GetCourseList(web136.SLCourse.GetCourseListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourseList", ReplyAction="http://tempuri.org/ISLCourse/GetCourseListResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.GetCourseListResponse> GetCourseListAsync(web136.SLCourse.GetCourseListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertCourse", ReplyAction="http://tempuri.org/ISLCourse/InsertCourseResponse")]
        web136.SLCourse.InsertCourseResponse InsertCourse(web136.SLCourse.InsertCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertCourse", ReplyAction="http://tempuri.org/ISLCourse/InsertCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.InsertCourseResponse> InsertCourseAsync(web136.SLCourse.InsertCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdateCourse", ReplyAction="http://tempuri.org/ISLCourse/UpdateCourseResponse")]
        web136.SLCourse.UpdateCourseResponse UpdateCourse(web136.SLCourse.UpdateCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdateCourse", ReplyAction="http://tempuri.org/ISLCourse/UpdateCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.UpdateCourseResponse> UpdateCourseAsync(web136.SLCourse.UpdateCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeleteCourse", ReplyAction="http://tempuri.org/ISLCourse/DeleteCourseResponse")]
        web136.SLCourse.DeleteCourseResponse DeleteCourse(web136.SLCourse.DeleteCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeleteCourse", ReplyAction="http://tempuri.org/ISLCourse/DeleteCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.DeleteCourseResponse> DeleteCourseAsync(web136.SLCourse.DeleteCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourse", ReplyAction="http://tempuri.org/ISLCourse/GetCourseResponse")]
        web136.SLCourse.GetCourseResponse GetCourse(web136.SLCourse.GetCourseRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/GetCourse", ReplyAction="http://tempuri.org/ISLCourse/GetCourseResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.GetCourseResponse> GetCourseAsync(web136.SLCourse.GetCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertPrerequisite", ReplyAction="http://tempuri.org/ISLCourse/InsertPrerequisiteResponse")]
        web136.SLCourse.InsertPrerequisiteResponse InsertPrerequisite(web136.SLCourse.InsertPrerequisiteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/InsertPrerequisite", ReplyAction="http://tempuri.org/ISLCourse/InsertPrerequisiteResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.InsertPrerequisiteResponse> InsertPrerequisiteAsync(web136.SLCourse.InsertPrerequisiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeletePrerequisite", ReplyAction="http://tempuri.org/ISLCourse/DeletePrerequisiteResponse")]
        web136.SLCourse.DeletePrerequisiteResponse DeletePrerequisite(web136.SLCourse.DeletePrerequisiteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/DeletePrerequisite", ReplyAction="http://tempuri.org/ISLCourse/DeletePrerequisiteResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.DeletePrerequisiteResponse> DeletePrerequisiteAsync(web136.SLCourse.DeletePrerequisiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdatePrerequisite", ReplyAction="http://tempuri.org/ISLCourse/UpdatePrerequisiteResponse")]
        web136.SLCourse.UpdatePrerequisiteResponse UpdatePrerequisite(web136.SLCourse.UpdatePrerequisiteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourse/UpdatePrerequisite", ReplyAction="http://tempuri.org/ISLCourse/UpdatePrerequisiteResponse")]
        System.Threading.Tasks.Task<web136.SLCourse.UpdatePrerequisiteResponse> UpdatePrerequisiteAsync(web136.SLCourse.UpdatePrerequisiteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetCourseListRequest() {
        }
        
        public GetCourseListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course[] GetCourseListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseListResponse() {
        }
        
        public GetCourseListResponse(web136.SLCourse.Course[] GetCourseListResult, string[] errors) {
            this.GetCourseListResult = GetCourseListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course course;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertCourseRequest() {
        }
        
        public InsertCourseRequest(web136.SLCourse.Course course, string[] errors) {
            this.course = course;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertCourseResponse() {
        }
        
        public InsertCourseResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course course;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateCourseRequest() {
        }
        
        public UpdateCourseRequest(web136.SLCourse.Course course, string[] errors) {
            this.course = course;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateCourseResponse() {
        }
        
        public UpdateCourseResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string coursetitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteCourseRequest() {
        }
        
        public DeleteCourseRequest(string coursetitle, string[] errors) {
            this.coursetitle = coursetitle;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteCourseResponse() {
        }
        
        public DeleteCourseResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string coursetitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseRequest() {
        }
        
        public GetCourseRequest(string coursetitle, string[] errors) {
            this.coursetitle = coursetitle;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLCourse.Course GetCourseResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseResponse() {
        }
        
        public GetCourseResponse(web136.SLCourse.Course GetCourseResult, string[] errors) {
            this.GetCourseResult = GetCourseResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPrerequisite", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPrerequisiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int courseid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pre_course_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public InsertPrerequisiteRequest() {
        }
        
        public InsertPrerequisiteRequest(int courseid, int pre_course_id, string[] errors) {
            this.courseid = courseid;
            this.pre_course_id = pre_course_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPrerequisiteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPrerequisiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertPrerequisiteResponse() {
        }
        
        public InsertPrerequisiteResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePrerequisite", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePrerequisiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int courseid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pre_course_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public DeletePrerequisiteRequest() {
        }
        
        public DeletePrerequisiteRequest(int courseid, int pre_course_id, string[] errors) {
            this.courseid = courseid;
            this.pre_course_id = pre_course_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePrerequisiteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePrerequisiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeletePrerequisiteResponse() {
        }
        
        public DeletePrerequisiteResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrerequisite", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePrerequisiteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int courseid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pre_course_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int change_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] errors;
        
        public UpdatePrerequisiteRequest() {
        }
        
        public UpdatePrerequisiteRequest(int courseid, int pre_course_id, int change_id, string[] errors) {
            this.courseid = courseid;
            this.pre_course_id = pre_course_id;
            this.change_id = change_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePrerequisiteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePrerequisiteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdatePrerequisiteResponse() {
        }
        
        public UpdatePrerequisiteResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLCourseChannel : web136.SLCourse.ISLCourse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLCourseClient : System.ServiceModel.ClientBase<web136.SLCourse.ISLCourse>, web136.SLCourse.ISLCourse {
        
        public SLCourseClient() {
        }
        
        public SLCourseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLCourseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.GetCourseListResponse web136.SLCourse.ISLCourse.GetCourseList(web136.SLCourse.GetCourseListRequest request) {
            return base.Channel.GetCourseList(request);
        }
        
        public web136.SLCourse.Course[] GetCourseList(ref string[] errors) {
            web136.SLCourse.GetCourseListRequest inValue = new web136.SLCourse.GetCourseListRequest();
            inValue.errors = errors;
            web136.SLCourse.GetCourseListResponse retVal = ((web136.SLCourse.ISLCourse)(this)).GetCourseList(inValue);
            errors = retVal.errors;
            return retVal.GetCourseListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.GetCourseListResponse> GetCourseListAsync(web136.SLCourse.GetCourseListRequest request) {
            return base.Channel.GetCourseListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.InsertCourseResponse web136.SLCourse.ISLCourse.InsertCourse(web136.SLCourse.InsertCourseRequest request) {
            return base.Channel.InsertCourse(request);
        }
        
        public void InsertCourse(web136.SLCourse.Course course, ref string[] errors) {
            web136.SLCourse.InsertCourseRequest inValue = new web136.SLCourse.InsertCourseRequest();
            inValue.course = course;
            inValue.errors = errors;
            web136.SLCourse.InsertCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).InsertCourse(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.InsertCourseResponse> InsertCourseAsync(web136.SLCourse.InsertCourseRequest request) {
            return base.Channel.InsertCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.UpdateCourseResponse web136.SLCourse.ISLCourse.UpdateCourse(web136.SLCourse.UpdateCourseRequest request) {
            return base.Channel.UpdateCourse(request);
        }
        
        public void UpdateCourse(web136.SLCourse.Course course, ref string[] errors) {
            web136.SLCourse.UpdateCourseRequest inValue = new web136.SLCourse.UpdateCourseRequest();
            inValue.course = course;
            inValue.errors = errors;
            web136.SLCourse.UpdateCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).UpdateCourse(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.UpdateCourseResponse> UpdateCourseAsync(web136.SLCourse.UpdateCourseRequest request) {
            return base.Channel.UpdateCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.DeleteCourseResponse web136.SLCourse.ISLCourse.DeleteCourse(web136.SLCourse.DeleteCourseRequest request) {
            return base.Channel.DeleteCourse(request);
        }
        
        public void DeleteCourse(string coursetitle, ref string[] errors) {
            web136.SLCourse.DeleteCourseRequest inValue = new web136.SLCourse.DeleteCourseRequest();
            inValue.coursetitle = coursetitle;
            inValue.errors = errors;
            web136.SLCourse.DeleteCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).DeleteCourse(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.DeleteCourseResponse> DeleteCourseAsync(web136.SLCourse.DeleteCourseRequest request) {
            return base.Channel.DeleteCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.GetCourseResponse web136.SLCourse.ISLCourse.GetCourse(web136.SLCourse.GetCourseRequest request) {
            return base.Channel.GetCourse(request);
        }
        
        public web136.SLCourse.Course GetCourse(string coursetitle, ref string[] errors) {
            web136.SLCourse.GetCourseRequest inValue = new web136.SLCourse.GetCourseRequest();
            inValue.coursetitle = coursetitle;
            inValue.errors = errors;
            web136.SLCourse.GetCourseResponse retVal = ((web136.SLCourse.ISLCourse)(this)).GetCourse(inValue);
            errors = retVal.errors;
            return retVal.GetCourseResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.GetCourseResponse> GetCourseAsync(web136.SLCourse.GetCourseRequest request) {
            return base.Channel.GetCourseAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.InsertPrerequisiteResponse web136.SLCourse.ISLCourse.InsertPrerequisite(web136.SLCourse.InsertPrerequisiteRequest request) {
            return base.Channel.InsertPrerequisite(request);
        }
        
        public void InsertPrerequisite(int courseid, int pre_course_id, ref string[] errors) {
            web136.SLCourse.InsertPrerequisiteRequest inValue = new web136.SLCourse.InsertPrerequisiteRequest();
            inValue.courseid = courseid;
            inValue.pre_course_id = pre_course_id;
            inValue.errors = errors;
            web136.SLCourse.InsertPrerequisiteResponse retVal = ((web136.SLCourse.ISLCourse)(this)).InsertPrerequisite(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.InsertPrerequisiteResponse> InsertPrerequisiteAsync(web136.SLCourse.InsertPrerequisiteRequest request) {
            return base.Channel.InsertPrerequisiteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.DeletePrerequisiteResponse web136.SLCourse.ISLCourse.DeletePrerequisite(web136.SLCourse.DeletePrerequisiteRequest request) {
            return base.Channel.DeletePrerequisite(request);
        }
        
        public void DeletePrerequisite(int courseid, int pre_course_id, ref string[] errors) {
            web136.SLCourse.DeletePrerequisiteRequest inValue = new web136.SLCourse.DeletePrerequisiteRequest();
            inValue.courseid = courseid;
            inValue.pre_course_id = pre_course_id;
            inValue.errors = errors;
            web136.SLCourse.DeletePrerequisiteResponse retVal = ((web136.SLCourse.ISLCourse)(this)).DeletePrerequisite(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.DeletePrerequisiteResponse> DeletePrerequisiteAsync(web136.SLCourse.DeletePrerequisiteRequest request) {
            return base.Channel.DeletePrerequisiteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLCourse.UpdatePrerequisiteResponse web136.SLCourse.ISLCourse.UpdatePrerequisite(web136.SLCourse.UpdatePrerequisiteRequest request) {
            return base.Channel.UpdatePrerequisite(request);
        }
        
        public void UpdatePrerequisite(int courseid, int pre_course_id, int change_id, ref string[] errors) {
            web136.SLCourse.UpdatePrerequisiteRequest inValue = new web136.SLCourse.UpdatePrerequisiteRequest();
            inValue.courseid = courseid;
            inValue.pre_course_id = pre_course_id;
            inValue.change_id = change_id;
            inValue.errors = errors;
            web136.SLCourse.UpdatePrerequisiteResponse retVal = ((web136.SLCourse.ISLCourse)(this)).UpdatePrerequisite(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLCourse.UpdatePrerequisiteResponse> UpdatePrerequisiteAsync(web136.SLCourse.UpdatePrerequisiteRequest request) {
            return base.Channel.UpdatePrerequisiteAsync(request);
        }
    }
}
