//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLStaff {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLStaff.Department deptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isInstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLStaff.Department dept {
            get {
                return this.deptField;
            }
            set {
                if ((object.ReferenceEquals(this.deptField, value) != true)) {
                    this.deptField = value;
                    this.RaisePropertyChanged("dept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isInstructor {
            get {
                return this.isInstructorField;
            }
            set {
                if ((this.isInstructorField.Equals(value) != true)) {
                    this.isInstructorField = value;
                    this.RaisePropertyChanged("isInstructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int chairIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int chairID {
            get {
                return this.chairIDField;
            }
            set {
                if ((this.chairIDField.Equals(value) != true)) {
                    this.chairIDField = value;
                    this.RaisePropertyChanged("chairID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deptName {
            get {
                return this.deptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.deptNameField, value) != true)) {
                    this.deptNameField = value;
                    this.RaisePropertyChanged("deptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLStaff.ISLStaff")]
    public interface ISLStaff {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/GetStaff", ReplyAction="http://tempuri.org/ISLStaff/GetStaffResponse")]
        web136.SLStaff.GetStaffResponse GetStaff(web136.SLStaff.GetStaffRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/GetStaff", ReplyAction="http://tempuri.org/ISLStaff/GetStaffResponse")]
        System.Threading.Tasks.Task<web136.SLStaff.GetStaffResponse> GetStaffAsync(web136.SLStaff.GetStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/InsertStaff", ReplyAction="http://tempuri.org/ISLStaff/InsertStaffResponse")]
        web136.SLStaff.InsertStaffResponse InsertStaff(web136.SLStaff.InsertStaffRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/InsertStaff", ReplyAction="http://tempuri.org/ISLStaff/InsertStaffResponse")]
        System.Threading.Tasks.Task<web136.SLStaff.InsertStaffResponse> InsertStaffAsync(web136.SLStaff.InsertStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/UpdateStaff", ReplyAction="http://tempuri.org/ISLStaff/UpdateStaffResponse")]
        web136.SLStaff.UpdateStaffResponse UpdateStaff(web136.SLStaff.UpdateStaffRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/UpdateStaff", ReplyAction="http://tempuri.org/ISLStaff/UpdateStaffResponse")]
        System.Threading.Tasks.Task<web136.SLStaff.UpdateStaffResponse> UpdateStaffAsync(web136.SLStaff.UpdateStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/DeleteStaff", ReplyAction="http://tempuri.org/ISLStaff/DeleteStaffResponse")]
        web136.SLStaff.DeleteStaffResponse DeleteStaff(web136.SLStaff.DeleteStaffRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/DeleteStaff", ReplyAction="http://tempuri.org/ISLStaff/DeleteStaffResponse")]
        System.Threading.Tasks.Task<web136.SLStaff.DeleteStaffResponse> DeleteStaffAsync(web136.SLStaff.DeleteStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/GetStaffList", ReplyAction="http://tempuri.org/ISLStaff/GetStaffListResponse")]
        web136.SLStaff.GetStaffListResponse GetStaffList(web136.SLStaff.GetStaffListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStaff/GetStaffList", ReplyAction="http://tempuri.org/ISLStaff/GetStaffListResponse")]
        System.Threading.Tasks.Task<web136.SLStaff.GetStaffListResponse> GetStaffListAsync(web136.SLStaff.GetStaffListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaff", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStaffRequest() {
        }
        
        public GetStaffRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaffResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStaff.Staff GetStaffResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStaffResponse() {
        }
        
        public GetStaffResponse(web136.SLStaff.Staff GetStaffResult, string[] errors) {
            this.GetStaffResult = GetStaffResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStaff", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStaff.Staff staffMember;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertStaffRequest() {
        }
        
        public InsertStaffRequest(web136.SLStaff.Staff staffMember, string[] errors) {
            this.staffMember = staffMember;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStaffResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertStaffResponse() {
        }
        
        public InsertStaffResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStaff", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStaff.Staff staffMember;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateStaffRequest() {
        }
        
        public UpdateStaffRequest(web136.SLStaff.Staff staffMember, string[] errors) {
            this.staffMember = staffMember;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStaffResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateStaffResponse() {
        }
        
        public UpdateStaffResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStaff", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteStaffRequest() {
        }
        
        public DeleteStaffRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStaffResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteStaffResponse() {
        }
        
        public DeleteStaffResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaffList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetStaffListRequest() {
        }
        
        public GetStaffListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStaffListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStaffListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStaff.Staff[] GetStaffListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStaffListResponse() {
        }
        
        public GetStaffListResponse(web136.SLStaff.Staff[] GetStaffListResult, string[] errors) {
            this.GetStaffListResult = GetStaffListResult;
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLStaffChannel : web136.SLStaff.ISLStaff, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLStaffClient : System.ServiceModel.ClientBase<web136.SLStaff.ISLStaff>, web136.SLStaff.ISLStaff {
        
        public SLStaffClient() {
        }
        
        public SLStaffClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLStaffClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLStaffClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLStaffClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStaff.GetStaffResponse web136.SLStaff.ISLStaff.GetStaff(web136.SLStaff.GetStaffRequest request) {
            return base.Channel.GetStaff(request);
        }
        
        public web136.SLStaff.Staff GetStaff(int id, ref string[] errors) {
            web136.SLStaff.GetStaffRequest inValue = new web136.SLStaff.GetStaffRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLStaff.GetStaffResponse retVal = ((web136.SLStaff.ISLStaff)(this)).GetStaff(inValue);
            errors = retVal.errors;
            return retVal.GetStaffResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLStaff.GetStaffResponse> GetStaffAsync(web136.SLStaff.GetStaffRequest request) {
            return base.Channel.GetStaffAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStaff.InsertStaffResponse web136.SLStaff.ISLStaff.InsertStaff(web136.SLStaff.InsertStaffRequest request) {
            return base.Channel.InsertStaff(request);
        }
        
        public void InsertStaff(web136.SLStaff.Staff staffMember, ref string[] errors) {
            web136.SLStaff.InsertStaffRequest inValue = new web136.SLStaff.InsertStaffRequest();
            inValue.staffMember = staffMember;
            inValue.errors = errors;
            web136.SLStaff.InsertStaffResponse retVal = ((web136.SLStaff.ISLStaff)(this)).InsertStaff(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStaff.InsertStaffResponse> InsertStaffAsync(web136.SLStaff.InsertStaffRequest request) {
            return base.Channel.InsertStaffAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStaff.UpdateStaffResponse web136.SLStaff.ISLStaff.UpdateStaff(web136.SLStaff.UpdateStaffRequest request) {
            return base.Channel.UpdateStaff(request);
        }
        
        public void UpdateStaff(web136.SLStaff.Staff staffMember, ref string[] errors) {
            web136.SLStaff.UpdateStaffRequest inValue = new web136.SLStaff.UpdateStaffRequest();
            inValue.staffMember = staffMember;
            inValue.errors = errors;
            web136.SLStaff.UpdateStaffResponse retVal = ((web136.SLStaff.ISLStaff)(this)).UpdateStaff(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStaff.UpdateStaffResponse> UpdateStaffAsync(web136.SLStaff.UpdateStaffRequest request) {
            return base.Channel.UpdateStaffAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStaff.DeleteStaffResponse web136.SLStaff.ISLStaff.DeleteStaff(web136.SLStaff.DeleteStaffRequest request) {
            return base.Channel.DeleteStaff(request);
        }
        
        public void DeleteStaff(int id, ref string[] errors) {
            web136.SLStaff.DeleteStaffRequest inValue = new web136.SLStaff.DeleteStaffRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLStaff.DeleteStaffResponse retVal = ((web136.SLStaff.ISLStaff)(this)).DeleteStaff(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStaff.DeleteStaffResponse> DeleteStaffAsync(web136.SLStaff.DeleteStaffRequest request) {
            return base.Channel.DeleteStaffAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStaff.GetStaffListResponse web136.SLStaff.ISLStaff.GetStaffList(web136.SLStaff.GetStaffListRequest request) {
            return base.Channel.GetStaffList(request);
        }
        
        public web136.SLStaff.Staff[] GetStaffList(ref string[] errors) {
            web136.SLStaff.GetStaffListRequest inValue = new web136.SLStaff.GetStaffListRequest();
            inValue.errors = errors;
            web136.SLStaff.GetStaffListResponse retVal = ((web136.SLStaff.ISLStaff)(this)).GetStaffList(inValue);
            errors = retVal.errors;
            return retVal.GetStaffListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLStaff.GetStaffListResponse> GetStaffListAsync(web136.SLStaff.GetStaffListRequest request) {
            return base.Channel.GetStaffListAsync(request);
        }
    }
}
