//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLEnrollment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enrollment", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Enrollment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLEnrollment.ScheduledCourse ScheduledCourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string student_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLEnrollment.ScheduledCourse ScheduledCourse {
            get {
                return this.ScheduledCourseField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduledCourseField, value) != true)) {
                    this.ScheduledCourseField = value;
                    this.RaisePropertyChanged("ScheduledCourse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                if ((object.ReferenceEquals(this.gradeField, value) != true)) {
                    this.gradeField = value;
                    this.RaisePropertyChanged("grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string student_id {
            get {
                return this.student_idField;
            }
            set {
                if ((object.ReferenceEquals(this.student_idField, value) != true)) {
                    this.student_idField = value;
                    this.RaisePropertyChanged("student_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledCourse", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class ScheduledCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLEnrollment.Course courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int instr_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructor_fNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructor_lNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLEnrollment.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string day {
            get {
                return this.dayField;
            }
            set {
                if ((object.ReferenceEquals(this.dayField, value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dayID {
            get {
                return this.dayIDField;
            }
            set {
                if ((this.dayIDField.Equals(value) != true)) {
                    this.dayIDField = value;
                    this.RaisePropertyChanged("dayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int instr_id {
            get {
                return this.instr_idField;
            }
            set {
                if ((this.instr_idField.Equals(value) != true)) {
                    this.instr_idField = value;
                    this.RaisePropertyChanged("instr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructor_fName {
            get {
                return this.instructor_fNameField;
            }
            set {
                if ((object.ReferenceEquals(this.instructor_fNameField, value) != true)) {
                    this.instructor_fNameField = value;
                    this.RaisePropertyChanged("instructor_fName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructor_lName {
            get {
                return this.instructor_lNameField;
            }
            set {
                if ((object.ReferenceEquals(this.instructor_lNameField, value) != true)) {
                    this.instructor_lNameField = value;
                    this.RaisePropertyChanged("instructor_lName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                if ((object.ReferenceEquals(this.quarterField, value) != true)) {
                    this.quarterField = value;
                    this.RaisePropertyChanged("quarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionField, value) != true)) {
                    this.sessionField = value;
                    this.RaisePropertyChanged("session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                if ((object.ReferenceEquals(this.timeField, value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int timeID {
            get {
                return this.timeIDField;
            }
            set {
                if ((this.timeIDField.Equals(value) != true)) {
                    this.timeIDField = value;
                    this.RaisePropertyChanged("timeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLEnrollment.Course[] prerequisite_listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int unitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLEnrollment.Course[] prerequisite_list {
            get {
                return this.prerequisite_listField;
            }
            set {
                if ((object.ReferenceEquals(this.prerequisite_listField, value) != true)) {
                    this.prerequisite_listField = value;
                    this.RaisePropertyChanged("prerequisite_list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                if ((this.unitsField.Equals(value) != true)) {
                    this.unitsField = value;
                    this.RaisePropertyChanged("units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLEnrollment.ISLEnrollment")]
    public interface ISLEnrollment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/GetEnrollmentList", ReplyAction="http://tempuri.org/ISLEnrollment/GetEnrollmentListResponse")]
        web136.SLEnrollment.GetEnrollmentListResponse GetEnrollmentList(web136.SLEnrollment.GetEnrollmentListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/GetEnrollmentList", ReplyAction="http://tempuri.org/ISLEnrollment/GetEnrollmentListResponse")]
        System.Threading.Tasks.Task<web136.SLEnrollment.GetEnrollmentListResponse> GetEnrollmentListAsync(web136.SLEnrollment.GetEnrollmentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/InsertEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/InsertEnrollmentResponse")]
        web136.SLEnrollment.InsertEnrollmentResponse InsertEnrollment(web136.SLEnrollment.InsertEnrollmentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/InsertEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/InsertEnrollmentResponse")]
        System.Threading.Tasks.Task<web136.SLEnrollment.InsertEnrollmentResponse> InsertEnrollmentAsync(web136.SLEnrollment.InsertEnrollmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/DeleteEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/DeleteEnrollmentResponse")]
        web136.SLEnrollment.DeleteEnrollmentResponse DeleteEnrollment(web136.SLEnrollment.DeleteEnrollmentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/DeleteEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/DeleteEnrollmentResponse")]
        System.Threading.Tasks.Task<web136.SLEnrollment.DeleteEnrollmentResponse> DeleteEnrollmentAsync(web136.SLEnrollment.DeleteEnrollmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/UpdateEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/UpdateEnrollmentResponse")]
        web136.SLEnrollment.UpdateEnrollmentResponse UpdateEnrollment(web136.SLEnrollment.UpdateEnrollmentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLEnrollment/UpdateEnrollment", ReplyAction="http://tempuri.org/ISLEnrollment/UpdateEnrollmentResponse")]
        System.Threading.Tasks.Task<web136.SLEnrollment.UpdateEnrollmentResponse> UpdateEnrollmentAsync(web136.SLEnrollment.UpdateEnrollmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnrollmentList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEnrollmentListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetEnrollmentListRequest() {
        }
        
        public GetEnrollmentListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEnrollmentListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEnrollmentListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLEnrollment.Enrollment[] GetEnrollmentListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetEnrollmentListResponse() {
        }
        
        public GetEnrollmentListResponse(web136.SLEnrollment.Enrollment[] GetEnrollmentListResult, string[] errors) {
            this.GetEnrollmentListResult = GetEnrollmentListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertEnrollment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertEnrollmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public InsertEnrollmentRequest() {
        }
        
        public InsertEnrollmentRequest(string student_id, int schedule_id, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertEnrollmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertEnrollmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertEnrollmentResponse() {
        }
        
        public InsertEnrollmentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEnrollment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteEnrollmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public DeleteEnrollmentRequest() {
        }
        
        public DeleteEnrollmentRequest(string student_id, int schedule_id, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEnrollmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteEnrollmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteEnrollmentResponse() {
        }
        
        public DeleteEnrollmentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEnrollment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEnrollmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string grade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] errors;
        
        public UpdateEnrollmentRequest() {
        }
        
        public UpdateEnrollmentRequest(string student_id, int schedule_id, string grade, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.grade = grade;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEnrollmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateEnrollmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateEnrollmentResponse() {
        }
        
        public UpdateEnrollmentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLEnrollmentChannel : web136.SLEnrollment.ISLEnrollment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLEnrollmentClient : System.ServiceModel.ClientBase<web136.SLEnrollment.ISLEnrollment>, web136.SLEnrollment.ISLEnrollment {
        
        public SLEnrollmentClient() {
        }
        
        public SLEnrollmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLEnrollmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLEnrollmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLEnrollmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLEnrollment.GetEnrollmentListResponse web136.SLEnrollment.ISLEnrollment.GetEnrollmentList(web136.SLEnrollment.GetEnrollmentListRequest request) {
            return base.Channel.GetEnrollmentList(request);
        }
        
        public web136.SLEnrollment.Enrollment[] GetEnrollmentList(ref string[] errors) {
            web136.SLEnrollment.GetEnrollmentListRequest inValue = new web136.SLEnrollment.GetEnrollmentListRequest();
            inValue.errors = errors;
            web136.SLEnrollment.GetEnrollmentListResponse retVal = ((web136.SLEnrollment.ISLEnrollment)(this)).GetEnrollmentList(inValue);
            errors = retVal.errors;
            return retVal.GetEnrollmentListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLEnrollment.GetEnrollmentListResponse> GetEnrollmentListAsync(web136.SLEnrollment.GetEnrollmentListRequest request) {
            return base.Channel.GetEnrollmentListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLEnrollment.InsertEnrollmentResponse web136.SLEnrollment.ISLEnrollment.InsertEnrollment(web136.SLEnrollment.InsertEnrollmentRequest request) {
            return base.Channel.InsertEnrollment(request);
        }
        
        public void InsertEnrollment(string student_id, int schedule_id, ref string[] errors) {
            web136.SLEnrollment.InsertEnrollmentRequest inValue = new web136.SLEnrollment.InsertEnrollmentRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.errors = errors;
            web136.SLEnrollment.InsertEnrollmentResponse retVal = ((web136.SLEnrollment.ISLEnrollment)(this)).InsertEnrollment(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLEnrollment.InsertEnrollmentResponse> InsertEnrollmentAsync(web136.SLEnrollment.InsertEnrollmentRequest request) {
            return base.Channel.InsertEnrollmentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLEnrollment.DeleteEnrollmentResponse web136.SLEnrollment.ISLEnrollment.DeleteEnrollment(web136.SLEnrollment.DeleteEnrollmentRequest request) {
            return base.Channel.DeleteEnrollment(request);
        }
        
        public void DeleteEnrollment(string student_id, int schedule_id, ref string[] errors) {
            web136.SLEnrollment.DeleteEnrollmentRequest inValue = new web136.SLEnrollment.DeleteEnrollmentRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.errors = errors;
            web136.SLEnrollment.DeleteEnrollmentResponse retVal = ((web136.SLEnrollment.ISLEnrollment)(this)).DeleteEnrollment(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLEnrollment.DeleteEnrollmentResponse> DeleteEnrollmentAsync(web136.SLEnrollment.DeleteEnrollmentRequest request) {
            return base.Channel.DeleteEnrollmentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLEnrollment.UpdateEnrollmentResponse web136.SLEnrollment.ISLEnrollment.UpdateEnrollment(web136.SLEnrollment.UpdateEnrollmentRequest request) {
            return base.Channel.UpdateEnrollment(request);
        }
        
        public void UpdateEnrollment(string student_id, int schedule_id, string grade, ref string[] errors) {
            web136.SLEnrollment.UpdateEnrollmentRequest inValue = new web136.SLEnrollment.UpdateEnrollmentRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.grade = grade;
            inValue.errors = errors;
            web136.SLEnrollment.UpdateEnrollmentResponse retVal = ((web136.SLEnrollment.ISLEnrollment)(this)).UpdateEnrollment(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLEnrollment.UpdateEnrollmentResponse> UpdateEnrollmentAsync(web136.SLEnrollment.UpdateEnrollmentRequest request) {
            return base.Channel.UpdateEnrollmentAsync(request);
        }
    }
}
