//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLMajor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Major", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Major : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int deptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string majorNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int deptId {
            get {
                return this.deptIdField;
            }
            set {
                if ((this.deptIdField.Equals(value) != true)) {
                    this.deptIdField = value;
                    this.RaisePropertyChanged("deptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string majorName {
            get {
                return this.majorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.majorNameField, value) != true)) {
                    this.majorNameField = value;
                    this.RaisePropertyChanged("majorName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLMajor.ISLMajor")]
    public interface ISLMajor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/InsertMajor", ReplyAction="http://tempuri.org/ISLMajor/InsertMajorResponse")]
        web136.SLMajor.InsertMajorResponse InsertMajor(web136.SLMajor.InsertMajorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/InsertMajor", ReplyAction="http://tempuri.org/ISLMajor/InsertMajorResponse")]
        System.Threading.Tasks.Task<web136.SLMajor.InsertMajorResponse> InsertMajorAsync(web136.SLMajor.InsertMajorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/UpdateMajor", ReplyAction="http://tempuri.org/ISLMajor/UpdateMajorResponse")]
        web136.SLMajor.UpdateMajorResponse UpdateMajor(web136.SLMajor.UpdateMajorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/UpdateMajor", ReplyAction="http://tempuri.org/ISLMajor/UpdateMajorResponse")]
        System.Threading.Tasks.Task<web136.SLMajor.UpdateMajorResponse> UpdateMajorAsync(web136.SLMajor.UpdateMajorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/DeleteMajor", ReplyAction="http://tempuri.org/ISLMajor/DeleteMajorResponse")]
        web136.SLMajor.DeleteMajorResponse DeleteMajor(web136.SLMajor.DeleteMajorRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/DeleteMajor", ReplyAction="http://tempuri.org/ISLMajor/DeleteMajorResponse")]
        System.Threading.Tasks.Task<web136.SLMajor.DeleteMajorResponse> DeleteMajorAsync(web136.SLMajor.DeleteMajorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/GetMajorDetail", ReplyAction="http://tempuri.org/ISLMajor/GetMajorDetailResponse")]
        web136.SLMajor.GetMajorDetailResponse GetMajorDetail(web136.SLMajor.GetMajorDetailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/GetMajorDetail", ReplyAction="http://tempuri.org/ISLMajor/GetMajorDetailResponse")]
        System.Threading.Tasks.Task<web136.SLMajor.GetMajorDetailResponse> GetMajorDetailAsync(web136.SLMajor.GetMajorDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/GetMajorList", ReplyAction="http://tempuri.org/ISLMajor/GetMajorListResponse")]
        web136.SLMajor.GetMajorListResponse GetMajorList(web136.SLMajor.GetMajorListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLMajor/GetMajorList", ReplyAction="http://tempuri.org/ISLMajor/GetMajorListResponse")]
        System.Threading.Tasks.Task<web136.SLMajor.GetMajorListResponse> GetMajorListAsync(web136.SLMajor.GetMajorListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertMajor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertMajorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLMajor.Major major;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertMajorRequest() {
        }
        
        public InsertMajorRequest(web136.SLMajor.Major major, string[] errors) {
            this.major = major;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertMajorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertMajorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertMajorResponse() {
        }
        
        public InsertMajorResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMajor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMajorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLMajor.Major major;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateMajorRequest() {
        }
        
        public UpdateMajorRequest(web136.SLMajor.Major major, string[] errors) {
            this.major = major;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMajorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMajorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateMajorResponse() {
        }
        
        public UpdateMajorResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteMajor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteMajorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteMajorRequest() {
        }
        
        public DeleteMajorRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteMajorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteMajorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteMajorResponse() {
        }
        
        public DeleteMajorResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMajorDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMajorDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetMajorDetailRequest() {
        }
        
        public GetMajorDetailRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMajorDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMajorDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLMajor.Major GetMajorDetailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetMajorDetailResponse() {
        }
        
        public GetMajorDetailResponse(web136.SLMajor.Major GetMajorDetailResult, string[] errors) {
            this.GetMajorDetailResult = GetMajorDetailResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMajorList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMajorListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetMajorListRequest() {
        }
        
        public GetMajorListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMajorListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMajorListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLMajor.Major[] GetMajorListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetMajorListResponse() {
        }
        
        public GetMajorListResponse(web136.SLMajor.Major[] GetMajorListResult, string[] errors) {
            this.GetMajorListResult = GetMajorListResult;
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLMajorChannel : web136.SLMajor.ISLMajor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLMajorClient : System.ServiceModel.ClientBase<web136.SLMajor.ISLMajor>, web136.SLMajor.ISLMajor {
        
        public SLMajorClient() {
        }
        
        public SLMajorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLMajorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMajorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLMajorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLMajor.InsertMajorResponse web136.SLMajor.ISLMajor.InsertMajor(web136.SLMajor.InsertMajorRequest request) {
            return base.Channel.InsertMajor(request);
        }
        
        public void InsertMajor(web136.SLMajor.Major major, ref string[] errors) {
            web136.SLMajor.InsertMajorRequest inValue = new web136.SLMajor.InsertMajorRequest();
            inValue.major = major;
            inValue.errors = errors;
            web136.SLMajor.InsertMajorResponse retVal = ((web136.SLMajor.ISLMajor)(this)).InsertMajor(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLMajor.InsertMajorResponse> InsertMajorAsync(web136.SLMajor.InsertMajorRequest request) {
            return base.Channel.InsertMajorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLMajor.UpdateMajorResponse web136.SLMajor.ISLMajor.UpdateMajor(web136.SLMajor.UpdateMajorRequest request) {
            return base.Channel.UpdateMajor(request);
        }
        
        public void UpdateMajor(web136.SLMajor.Major major, ref string[] errors) {
            web136.SLMajor.UpdateMajorRequest inValue = new web136.SLMajor.UpdateMajorRequest();
            inValue.major = major;
            inValue.errors = errors;
            web136.SLMajor.UpdateMajorResponse retVal = ((web136.SLMajor.ISLMajor)(this)).UpdateMajor(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLMajor.UpdateMajorResponse> UpdateMajorAsync(web136.SLMajor.UpdateMajorRequest request) {
            return base.Channel.UpdateMajorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLMajor.DeleteMajorResponse web136.SLMajor.ISLMajor.DeleteMajor(web136.SLMajor.DeleteMajorRequest request) {
            return base.Channel.DeleteMajor(request);
        }
        
        public void DeleteMajor(int id, ref string[] errors) {
            web136.SLMajor.DeleteMajorRequest inValue = new web136.SLMajor.DeleteMajorRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLMajor.DeleteMajorResponse retVal = ((web136.SLMajor.ISLMajor)(this)).DeleteMajor(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLMajor.DeleteMajorResponse> DeleteMajorAsync(web136.SLMajor.DeleteMajorRequest request) {
            return base.Channel.DeleteMajorAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLMajor.GetMajorDetailResponse web136.SLMajor.ISLMajor.GetMajorDetail(web136.SLMajor.GetMajorDetailRequest request) {
            return base.Channel.GetMajorDetail(request);
        }
        
        public web136.SLMajor.Major GetMajorDetail(int id, ref string[] errors) {
            web136.SLMajor.GetMajorDetailRequest inValue = new web136.SLMajor.GetMajorDetailRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLMajor.GetMajorDetailResponse retVal = ((web136.SLMajor.ISLMajor)(this)).GetMajorDetail(inValue);
            errors = retVal.errors;
            return retVal.GetMajorDetailResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLMajor.GetMajorDetailResponse> GetMajorDetailAsync(web136.SLMajor.GetMajorDetailRequest request) {
            return base.Channel.GetMajorDetailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLMajor.GetMajorListResponse web136.SLMajor.ISLMajor.GetMajorList(web136.SLMajor.GetMajorListRequest request) {
            return base.Channel.GetMajorList(request);
        }
        
        public web136.SLMajor.Major[] GetMajorList(ref string[] errors) {
            web136.SLMajor.GetMajorListRequest inValue = new web136.SLMajor.GetMajorListRequest();
            inValue.errors = errors;
            web136.SLMajor.GetMajorListResponse retVal = ((web136.SLMajor.ISLMajor)(this)).GetMajorList(inValue);
            errors = retVal.errors;
            return retVal.GetMajorListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLMajor.GetMajorListResponse> GetMajorListAsync(web136.SLMajor.GetMajorListRequest request) {
            return base.Channel.GetMajorListAsync(request);
        }
    }
}
