//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLSchedule {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduledCourse", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class ScheduledCourse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLSchedule.Course courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int instr_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructor_fNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instructor_lNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int timeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLSchedule.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string day {
            get {
                return this.dayField;
            }
            set {
                if ((object.ReferenceEquals(this.dayField, value) != true)) {
                    this.dayField = value;
                    this.RaisePropertyChanged("day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dayID {
            get {
                return this.dayIDField;
            }
            set {
                if ((this.dayIDField.Equals(value) != true)) {
                    this.dayIDField = value;
                    this.RaisePropertyChanged("dayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int instr_id {
            get {
                return this.instr_idField;
            }
            set {
                if ((this.instr_idField.Equals(value) != true)) {
                    this.instr_idField = value;
                    this.RaisePropertyChanged("instr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructor_fName {
            get {
                return this.instructor_fNameField;
            }
            set {
                if ((object.ReferenceEquals(this.instructor_fNameField, value) != true)) {
                    this.instructor_fNameField = value;
                    this.RaisePropertyChanged("instructor_fName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instructor_lName {
            get {
                return this.instructor_lNameField;
            }
            set {
                if ((object.ReferenceEquals(this.instructor_lNameField, value) != true)) {
                    this.instructor_lNameField = value;
                    this.RaisePropertyChanged("instructor_lName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                if ((object.ReferenceEquals(this.quarterField, value) != true)) {
                    this.quarterField = value;
                    this.RaisePropertyChanged("quarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionField, value) != true)) {
                    this.sessionField = value;
                    this.RaisePropertyChanged("session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                if ((object.ReferenceEquals(this.timeField, value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int timeID {
            get {
                return this.timeIDField;
            }
            set {
                if ((this.timeIDField.Equals(value) != true)) {
                    this.timeIDField = value;
                    this.RaisePropertyChanged("timeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLSchedule.Course[] prerequisite_listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int unitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                if ((object.ReferenceEquals(this.levelField, value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLSchedule.Course[] prerequisite_list {
            get {
                return this.prerequisite_listField;
            }
            set {
                if ((object.ReferenceEquals(this.prerequisite_listField, value) != true)) {
                    this.prerequisite_listField = value;
                    this.RaisePropertyChanged("prerequisite_list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int units {
            get {
                return this.unitsField;
            }
            set {
                if ((this.unitsField.Equals(value) != true)) {
                    this.unitsField = value;
                    this.RaisePropertyChanged("units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLSchedule.ISLCourseSchedule")]
    public interface ISLCourseSchedule {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetScheduleList", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetScheduleListResponse")]
        web136.SLSchedule.GetScheduleListResponse GetScheduleList(web136.SLSchedule.GetScheduleListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetScheduleList", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetScheduleListResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListResponse> GetScheduleListAsync(web136.SLSchedule.GetScheduleListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetScheduleListComplete", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetScheduleListCompleteResponse")]
        web136.SLSchedule.GetScheduleListCompleteResponse GetScheduleListComplete(web136.SLSchedule.GetScheduleListCompleteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetScheduleListComplete", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetScheduleListCompleteResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListCompleteResponse> GetScheduleListCompleteAsync(web136.SLSchedule.GetScheduleListCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/InsertCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/InsertCourseScheduleResponse")]
        web136.SLSchedule.InsertCourseScheduleResponse InsertCourseSchedule(web136.SLSchedule.InsertCourseScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/InsertCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/InsertCourseScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.InsertCourseScheduleResponse> InsertCourseScheduleAsync(web136.SLSchedule.InsertCourseScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/UpdateCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/UpdateCourseScheduleResponse")]
        web136.SLSchedule.UpdateCourseScheduleResponse UpdateCourseSchedule(web136.SLSchedule.UpdateCourseScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/UpdateCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/UpdateCourseScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.UpdateCourseScheduleResponse> UpdateCourseScheduleAsync(web136.SLSchedule.UpdateCourseScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/DeleteCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/DeleteCourseScheduleResponse")]
        web136.SLSchedule.DeleteCourseScheduleResponse DeleteCourseSchedule(web136.SLSchedule.DeleteCourseScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/DeleteCourseSchedule", ReplyAction="http://tempuri.org/ISLCourseSchedule/DeleteCourseScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.DeleteCourseScheduleResponse> DeleteCourseScheduleAsync(web136.SLSchedule.DeleteCourseScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetCourseScheduleDetail", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetCourseScheduleDetailResponse")]
        web136.SLSchedule.GetCourseScheduleDetailResponse GetCourseScheduleDetail(web136.SLSchedule.GetCourseScheduleDetailRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLCourseSchedule/GetCourseScheduleDetail", ReplyAction="http://tempuri.org/ISLCourseSchedule/GetCourseScheduleDetailResponse")]
        System.Threading.Tasks.Task<web136.SLSchedule.GetCourseScheduleDetailResponse> GetCourseScheduleDetailAsync(web136.SLSchedule.GetCourseScheduleDetailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string quarter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public GetScheduleListRequest() {
        }
        
        public GetScheduleListRequest(int year, string quarter, string[] errors) {
            this.year = year;
            this.quarter = quarter;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.ScheduledCourse[] GetScheduleListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleListResponse() {
        }
        
        public GetScheduleListResponse(web136.SLSchedule.ScheduledCourse[] GetScheduleListResult, string[] errors) {
            this.GetScheduleListResult = GetScheduleListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleListComplete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetScheduleListCompleteRequest() {
        }
        
        public GetScheduleListCompleteRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleListCompleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleListCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.ScheduledCourse[] GetScheduleListCompleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleListCompleteResponse() {
        }
        
        public GetScheduleListCompleteResponse(web136.SLSchedule.ScheduledCourse[] GetScheduleListCompleteResult, string[] errors) {
            this.GetScheduleListCompleteResult = GetScheduleListCompleteResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourseSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.ScheduledCourse sched;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertCourseScheduleRequest() {
        }
        
        public InsertCourseScheduleRequest(web136.SLSchedule.ScheduledCourse sched, string[] errors) {
            this.sched = sched;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertCourseScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertCourseScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        public InsertCourseScheduleResponse() {
        }
        
        public InsertCourseScheduleResponse(string[] errors, int ID) {
            this.errors = errors;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourseSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.ScheduledCourse sched;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateCourseScheduleRequest() {
        }
        
        public UpdateCourseScheduleRequest(web136.SLSchedule.ScheduledCourse sched, string[] errors) {
            this.sched = sched;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCourseScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCourseScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateCourseScheduleResponse() {
        }
        
        public UpdateCourseScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourseSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteCourseScheduleRequest() {
        }
        
        public DeleteCourseScheduleRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCourseScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteCourseScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteCourseScheduleResponse() {
        }
        
        public DeleteCourseScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseScheduleDetail", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseScheduleDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseScheduleDetailRequest() {
        }
        
        public GetCourseScheduleDetailRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCourseScheduleDetailResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCourseScheduleDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLSchedule.ScheduledCourse GetCourseScheduleDetailResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetCourseScheduleDetailResponse() {
        }
        
        public GetCourseScheduleDetailResponse(web136.SLSchedule.ScheduledCourse GetCourseScheduleDetailResult, string[] errors) {
            this.GetCourseScheduleDetailResult = GetCourseScheduleDetailResult;
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLCourseScheduleChannel : web136.SLSchedule.ISLCourseSchedule, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLCourseScheduleClient : System.ServiceModel.ClientBase<web136.SLSchedule.ISLCourseSchedule>, web136.SLSchedule.ISLCourseSchedule {
        
        public SLCourseScheduleClient() {
        }
        
        public SLCourseScheduleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLCourseScheduleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseScheduleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLCourseScheduleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetScheduleListResponse web136.SLSchedule.ISLCourseSchedule.GetScheduleList(web136.SLSchedule.GetScheduleListRequest request) {
            return base.Channel.GetScheduleList(request);
        }
        
        public web136.SLSchedule.ScheduledCourse[] GetScheduleList(int year, string quarter, ref string[] errors) {
            web136.SLSchedule.GetScheduleListRequest inValue = new web136.SLSchedule.GetScheduleListRequest();
            inValue.year = year;
            inValue.quarter = quarter;
            inValue.errors = errors;
            web136.SLSchedule.GetScheduleListResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).GetScheduleList(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListResponse> GetScheduleListAsync(web136.SLSchedule.GetScheduleListRequest request) {
            return base.Channel.GetScheduleListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetScheduleListCompleteResponse web136.SLSchedule.ISLCourseSchedule.GetScheduleListComplete(web136.SLSchedule.GetScheduleListCompleteRequest request) {
            return base.Channel.GetScheduleListComplete(request);
        }
        
        public web136.SLSchedule.ScheduledCourse[] GetScheduleListComplete(ref string[] errors) {
            web136.SLSchedule.GetScheduleListCompleteRequest inValue = new web136.SLSchedule.GetScheduleListCompleteRequest();
            inValue.errors = errors;
            web136.SLSchedule.GetScheduleListCompleteResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).GetScheduleListComplete(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleListCompleteResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetScheduleListCompleteResponse> GetScheduleListCompleteAsync(web136.SLSchedule.GetScheduleListCompleteRequest request) {
            return base.Channel.GetScheduleListCompleteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.InsertCourseScheduleResponse web136.SLSchedule.ISLCourseSchedule.InsertCourseSchedule(web136.SLSchedule.InsertCourseScheduleRequest request) {
            return base.Channel.InsertCourseSchedule(request);
        }
        
        public int InsertCourseSchedule(web136.SLSchedule.ScheduledCourse sched, ref string[] errors) {
            web136.SLSchedule.InsertCourseScheduleRequest inValue = new web136.SLSchedule.InsertCourseScheduleRequest();
            inValue.sched = sched;
            inValue.errors = errors;
            web136.SLSchedule.InsertCourseScheduleResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).InsertCourseSchedule(inValue);
            errors = retVal.errors;
            return retVal.ID;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.InsertCourseScheduleResponse> InsertCourseScheduleAsync(web136.SLSchedule.InsertCourseScheduleRequest request) {
            return base.Channel.InsertCourseScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.UpdateCourseScheduleResponse web136.SLSchedule.ISLCourseSchedule.UpdateCourseSchedule(web136.SLSchedule.UpdateCourseScheduleRequest request) {
            return base.Channel.UpdateCourseSchedule(request);
        }
        
        public void UpdateCourseSchedule(web136.SLSchedule.ScheduledCourse sched, ref string[] errors) {
            web136.SLSchedule.UpdateCourseScheduleRequest inValue = new web136.SLSchedule.UpdateCourseScheduleRequest();
            inValue.sched = sched;
            inValue.errors = errors;
            web136.SLSchedule.UpdateCourseScheduleResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).UpdateCourseSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.UpdateCourseScheduleResponse> UpdateCourseScheduleAsync(web136.SLSchedule.UpdateCourseScheduleRequest request) {
            return base.Channel.UpdateCourseScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.DeleteCourseScheduleResponse web136.SLSchedule.ISLCourseSchedule.DeleteCourseSchedule(web136.SLSchedule.DeleteCourseScheduleRequest request) {
            return base.Channel.DeleteCourseSchedule(request);
        }
        
        public void DeleteCourseSchedule(int id, ref string[] errors) {
            web136.SLSchedule.DeleteCourseScheduleRequest inValue = new web136.SLSchedule.DeleteCourseScheduleRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLSchedule.DeleteCourseScheduleResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).DeleteCourseSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.DeleteCourseScheduleResponse> DeleteCourseScheduleAsync(web136.SLSchedule.DeleteCourseScheduleRequest request) {
            return base.Channel.DeleteCourseScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLSchedule.GetCourseScheduleDetailResponse web136.SLSchedule.ISLCourseSchedule.GetCourseScheduleDetail(web136.SLSchedule.GetCourseScheduleDetailRequest request) {
            return base.Channel.GetCourseScheduleDetail(request);
        }
        
        public web136.SLSchedule.ScheduledCourse GetCourseScheduleDetail(int id, ref string[] errors) {
            web136.SLSchedule.GetCourseScheduleDetailRequest inValue = new web136.SLSchedule.GetCourseScheduleDetailRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLSchedule.GetCourseScheduleDetailResponse retVal = ((web136.SLSchedule.ISLCourseSchedule)(this)).GetCourseScheduleDetail(inValue);
            errors = retVal.errors;
            return retVal.GetCourseScheduleDetailResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLSchedule.GetCourseScheduleDetailResponse> GetCourseScheduleDetailAsync(web136.SLSchedule.GetCourseScheduleDetailRequest request) {
            return base.Channel.GetCourseScheduleDetailAsync(request);
        }
    }
}
