//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLScheduleDay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLScheduleDay.ISLScheduleDay")]
    public interface ISLScheduleDay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/GetScheduleDayList", ReplyAction="http://tempuri.org/ISLScheduleDay/GetScheduleDayListResponse")]
        web136.SLScheduleDay.GetScheduleDayListResponse GetScheduleDayList(web136.SLScheduleDay.GetScheduleDayListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/GetScheduleDayList", ReplyAction="http://tempuri.org/ISLScheduleDay/GetScheduleDayListResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleDay.GetScheduleDayListResponse> GetScheduleDayListAsync(web136.SLScheduleDay.GetScheduleDayListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/InsertScheduleDay", ReplyAction="http://tempuri.org/ISLScheduleDay/InsertScheduleDayResponse")]
        web136.SLScheduleDay.InsertScheduleDayResponse InsertScheduleDay(web136.SLScheduleDay.InsertScheduleDayRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/InsertScheduleDay", ReplyAction="http://tempuri.org/ISLScheduleDay/InsertScheduleDayResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleDay.InsertScheduleDayResponse> InsertScheduleDayAsync(web136.SLScheduleDay.InsertScheduleDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/DeleteScheduleDay", ReplyAction="http://tempuri.org/ISLScheduleDay/DeleteScheduleDayResponse")]
        web136.SLScheduleDay.DeleteScheduleDayResponse DeleteScheduleDay(web136.SLScheduleDay.DeleteScheduleDayRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleDay/DeleteScheduleDay", ReplyAction="http://tempuri.org/ISLScheduleDay/DeleteScheduleDayResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleDay.DeleteScheduleDayResponse> DeleteScheduleDayAsync(web136.SLScheduleDay.DeleteScheduleDayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleDayList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleDayListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetScheduleDayListRequest() {
        }
        
        public GetScheduleDayListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleDayListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleDayListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] GetScheduleDayListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleDayListResponse() {
        }
        
        public GetScheduleDayListResponse(string[] GetScheduleDayListResult, string[] errors) {
            this.GetScheduleDayListResult = GetScheduleDayListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertScheduleDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertScheduleDayRequest() {
        }
        
        public InsertScheduleDayRequest(string day, string[] errors) {
            this.day = day;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertScheduleDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertScheduleDayResponse() {
        }
        
        public InsertScheduleDayResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScheduleDay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteScheduleDayRequest() {
        }
        
        public DeleteScheduleDayRequest(string id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScheduleDayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteScheduleDayResponse() {
        }
        
        public DeleteScheduleDayResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLScheduleDayChannel : web136.SLScheduleDay.ISLScheduleDay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLScheduleDayClient : System.ServiceModel.ClientBase<web136.SLScheduleDay.ISLScheduleDay>, web136.SLScheduleDay.ISLScheduleDay {
        
        public SLScheduleDayClient() {
        }
        
        public SLScheduleDayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLScheduleDayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleDayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleDayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleDay.GetScheduleDayListResponse web136.SLScheduleDay.ISLScheduleDay.GetScheduleDayList(web136.SLScheduleDay.GetScheduleDayListRequest request) {
            return base.Channel.GetScheduleDayList(request);
        }
        
        public string[] GetScheduleDayList(ref string[] errors) {
            web136.SLScheduleDay.GetScheduleDayListRequest inValue = new web136.SLScheduleDay.GetScheduleDayListRequest();
            inValue.errors = errors;
            web136.SLScheduleDay.GetScheduleDayListResponse retVal = ((web136.SLScheduleDay.ISLScheduleDay)(this)).GetScheduleDayList(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleDayListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleDay.GetScheduleDayListResponse> GetScheduleDayListAsync(web136.SLScheduleDay.GetScheduleDayListRequest request) {
            return base.Channel.GetScheduleDayListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleDay.InsertScheduleDayResponse web136.SLScheduleDay.ISLScheduleDay.InsertScheduleDay(web136.SLScheduleDay.InsertScheduleDayRequest request) {
            return base.Channel.InsertScheduleDay(request);
        }
        
        public void InsertScheduleDay(string day, ref string[] errors) {
            web136.SLScheduleDay.InsertScheduleDayRequest inValue = new web136.SLScheduleDay.InsertScheduleDayRequest();
            inValue.day = day;
            inValue.errors = errors;
            web136.SLScheduleDay.InsertScheduleDayResponse retVal = ((web136.SLScheduleDay.ISLScheduleDay)(this)).InsertScheduleDay(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleDay.InsertScheduleDayResponse> InsertScheduleDayAsync(web136.SLScheduleDay.InsertScheduleDayRequest request) {
            return base.Channel.InsertScheduleDayAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleDay.DeleteScheduleDayResponse web136.SLScheduleDay.ISLScheduleDay.DeleteScheduleDay(web136.SLScheduleDay.DeleteScheduleDayRequest request) {
            return base.Channel.DeleteScheduleDay(request);
        }
        
        public void DeleteScheduleDay(string id, ref string[] errors) {
            web136.SLScheduleDay.DeleteScheduleDayRequest inValue = new web136.SLScheduleDay.DeleteScheduleDayRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLScheduleDay.DeleteScheduleDayResponse retVal = ((web136.SLScheduleDay.ISLScheduleDay)(this)).DeleteScheduleDay(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleDay.DeleteScheduleDayResponse> DeleteScheduleDayAsync(web136.SLScheduleDay.DeleteScheduleDayRequest request) {
            return base.Channel.DeleteScheduleDayAsync(request);
        }
    }
}
