//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLStudent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLStudent.Schedule[] enrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float shoe_sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ssnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int weightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLStudent.Schedule[] enrolled {
            get {
                return this.enrolledField;
            }
            set {
                if ((object.ReferenceEquals(this.enrolledField, value) != true)) {
                    this.enrolledField = value;
                    this.RaisePropertyChanged("enrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float shoe_size {
            get {
                return this.shoe_sizeField;
            }
            set {
                if ((this.shoe_sizeField.Equals(value) != true)) {
                    this.shoe_sizeField = value;
                    this.RaisePropertyChanged("shoe_size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ssn {
            get {
                return this.ssnField;
            }
            set {
                if ((object.ReferenceEquals(this.ssnField, value) != true)) {
                    this.ssnField = value;
                    this.RaisePropertyChanged("ssn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private web136.SLStudent.Course courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quarterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public web136.SLStudent.Course course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                if ((object.ReferenceEquals(this.quarterField, value) != true)) {
                    this.quarterField = value;
                    this.RaisePropertyChanged("quarter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string session {
            get {
                return this.sessionField;
            }
            set {
                if ((object.ReferenceEquals(this.sessionField, value) != true)) {
                    this.sessionField = value;
                    this.RaisePropertyChanged("session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                if ((object.ReferenceEquals(this.yearField, value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLStudent.ISLStudent")]
    public interface ISLStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/GetStudent", ReplyAction="http://tempuri.org/ISLStudent/GetStudentResponse")]
        web136.SLStudent.GetStudentResponse GetStudent(web136.SLStudent.GetStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/GetStudent", ReplyAction="http://tempuri.org/ISLStudent/GetStudentResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.GetStudentResponse> GetStudentAsync(web136.SLStudent.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/InsertStudent", ReplyAction="http://tempuri.org/ISLStudent/InsertStudentResponse")]
        web136.SLStudent.InsertStudentResponse InsertStudent(web136.SLStudent.InsertStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/InsertStudent", ReplyAction="http://tempuri.org/ISLStudent/InsertStudentResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.InsertStudentResponse> InsertStudentAsync(web136.SLStudent.InsertStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/UpdateStudent", ReplyAction="http://tempuri.org/ISLStudent/UpdateStudentResponse")]
        web136.SLStudent.UpdateStudentResponse UpdateStudent(web136.SLStudent.UpdateStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/UpdateStudent", ReplyAction="http://tempuri.org/ISLStudent/UpdateStudentResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.UpdateStudentResponse> UpdateStudentAsync(web136.SLStudent.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/DeleteStudent", ReplyAction="http://tempuri.org/ISLStudent/DeleteStudentResponse")]
        web136.SLStudent.DeleteStudentResponse DeleteStudent(web136.SLStudent.DeleteStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/DeleteStudent", ReplyAction="http://tempuri.org/ISLStudent/DeleteStudentResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.DeleteStudentResponse> DeleteStudentAsync(web136.SLStudent.DeleteStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/GetStudentList", ReplyAction="http://tempuri.org/ISLStudent/GetStudentListResponse")]
        web136.SLStudent.GetStudentListResponse GetStudentList(web136.SLStudent.GetStudentListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/GetStudentList", ReplyAction="http://tempuri.org/ISLStudent/GetStudentListResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.GetStudentListResponse> GetStudentListAsync(web136.SLStudent.GetStudentListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/EnrollSchedule", ReplyAction="http://tempuri.org/ISLStudent/EnrollScheduleResponse")]
        web136.SLStudent.EnrollScheduleResponse EnrollSchedule(web136.SLStudent.EnrollScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/EnrollSchedule", ReplyAction="http://tempuri.org/ISLStudent/EnrollScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.EnrollScheduleResponse> EnrollScheduleAsync(web136.SLStudent.EnrollScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/DropEnrolledSchedule", ReplyAction="http://tempuri.org/ISLStudent/DropEnrolledScheduleResponse")]
        web136.SLStudent.DropEnrolledScheduleResponse DropEnrolledSchedule(web136.SLStudent.DropEnrolledScheduleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLStudent/DropEnrolledSchedule", ReplyAction="http://tempuri.org/ISLStudent/DropEnrolledScheduleResponse")]
        System.Threading.Tasks.Task<web136.SLStudent.DropEnrolledScheduleResponse> DropEnrolledScheduleAsync(web136.SLStudent.DropEnrolledScheduleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStudentRequest() {
        }
        
        public GetStudentRequest(string id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStudent.Student GetStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStudentResponse() {
        }
        
        public GetStudentResponse(web136.SLStudent.Student GetStudentResult, string[] errors) {
            this.GetStudentResult = GetStudentResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStudent.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertStudentRequest() {
        }
        
        public InsertStudentRequest(web136.SLStudent.Student student, string[] errors) {
            this.student = student;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertStudentResponse() {
        }
        
        public InsertStudentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStudent.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public UpdateStudentRequest() {
        }
        
        public UpdateStudentRequest(web136.SLStudent.Student student, string[] errors) {
            this.student = student;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public UpdateStudentResponse() {
        }
        
        public UpdateStudentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteStudentRequest() {
        }
        
        public DeleteStudentRequest(string id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteStudentResponse() {
        }
        
        public DeleteStudentResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetStudentListRequest() {
        }
        
        public GetStudentListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLStudent.Student[] GetStudentListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetStudentListResponse() {
        }
        
        public GetStudentListResponse(web136.SLStudent.Student[] GetStudentListResult, string[] errors) {
            this.GetStudentListResult = GetStudentListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnrollScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public EnrollScheduleRequest() {
        }
        
        public EnrollScheduleRequest(string student_id, int schedule_id, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnrollScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public EnrollScheduleResponse() {
        }
        
        public EnrollScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DropEnrolledSchedule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DropEnrolledScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string student_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int schedule_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public DropEnrolledScheduleRequest() {
        }
        
        public DropEnrolledScheduleRequest(string student_id, int schedule_id, string[] errors) {
            this.student_id = student_id;
            this.schedule_id = schedule_id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DropEnrolledScheduleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DropEnrolledScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DropEnrolledScheduleResponse() {
        }
        
        public DropEnrolledScheduleResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLStudentChannel : web136.SLStudent.ISLStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLStudentClient : System.ServiceModel.ClientBase<web136.SLStudent.ISLStudent>, web136.SLStudent.ISLStudent {
        
        public SLStudentClient() {
        }
        
        public SLStudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLStudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLStudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLStudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.GetStudentResponse web136.SLStudent.ISLStudent.GetStudent(web136.SLStudent.GetStudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public web136.SLStudent.Student GetStudent(string id, ref string[] errors) {
            web136.SLStudent.GetStudentRequest inValue = new web136.SLStudent.GetStudentRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLStudent.GetStudentResponse retVal = ((web136.SLStudent.ISLStudent)(this)).GetStudent(inValue);
            errors = retVal.errors;
            return retVal.GetStudentResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.GetStudentResponse> GetStudentAsync(web136.SLStudent.GetStudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.InsertStudentResponse web136.SLStudent.ISLStudent.InsertStudent(web136.SLStudent.InsertStudentRequest request) {
            return base.Channel.InsertStudent(request);
        }
        
        public void InsertStudent(web136.SLStudent.Student student, ref string[] errors) {
            web136.SLStudent.InsertStudentRequest inValue = new web136.SLStudent.InsertStudentRequest();
            inValue.student = student;
            inValue.errors = errors;
            web136.SLStudent.InsertStudentResponse retVal = ((web136.SLStudent.ISLStudent)(this)).InsertStudent(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.InsertStudentResponse> InsertStudentAsync(web136.SLStudent.InsertStudentRequest request) {
            return base.Channel.InsertStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.UpdateStudentResponse web136.SLStudent.ISLStudent.UpdateStudent(web136.SLStudent.UpdateStudentRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public void UpdateStudent(web136.SLStudent.Student student, ref string[] errors) {
            web136.SLStudent.UpdateStudentRequest inValue = new web136.SLStudent.UpdateStudentRequest();
            inValue.student = student;
            inValue.errors = errors;
            web136.SLStudent.UpdateStudentResponse retVal = ((web136.SLStudent.ISLStudent)(this)).UpdateStudent(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.UpdateStudentResponse> UpdateStudentAsync(web136.SLStudent.UpdateStudentRequest request) {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.DeleteStudentResponse web136.SLStudent.ISLStudent.DeleteStudent(web136.SLStudent.DeleteStudentRequest request) {
            return base.Channel.DeleteStudent(request);
        }
        
        public void DeleteStudent(string id, ref string[] errors) {
            web136.SLStudent.DeleteStudentRequest inValue = new web136.SLStudent.DeleteStudentRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLStudent.DeleteStudentResponse retVal = ((web136.SLStudent.ISLStudent)(this)).DeleteStudent(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.DeleteStudentResponse> DeleteStudentAsync(web136.SLStudent.DeleteStudentRequest request) {
            return base.Channel.DeleteStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.GetStudentListResponse web136.SLStudent.ISLStudent.GetStudentList(web136.SLStudent.GetStudentListRequest request) {
            return base.Channel.GetStudentList(request);
        }
        
        public web136.SLStudent.Student[] GetStudentList(ref string[] errors) {
            web136.SLStudent.GetStudentListRequest inValue = new web136.SLStudent.GetStudentListRequest();
            inValue.errors = errors;
            web136.SLStudent.GetStudentListResponse retVal = ((web136.SLStudent.ISLStudent)(this)).GetStudentList(inValue);
            errors = retVal.errors;
            return retVal.GetStudentListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.GetStudentListResponse> GetStudentListAsync(web136.SLStudent.GetStudentListRequest request) {
            return base.Channel.GetStudentListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.EnrollScheduleResponse web136.SLStudent.ISLStudent.EnrollSchedule(web136.SLStudent.EnrollScheduleRequest request) {
            return base.Channel.EnrollSchedule(request);
        }
        
        public void EnrollSchedule(string student_id, int schedule_id, ref string[] errors) {
            web136.SLStudent.EnrollScheduleRequest inValue = new web136.SLStudent.EnrollScheduleRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.errors = errors;
            web136.SLStudent.EnrollScheduleResponse retVal = ((web136.SLStudent.ISLStudent)(this)).EnrollSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.EnrollScheduleResponse> EnrollScheduleAsync(web136.SLStudent.EnrollScheduleRequest request) {
            return base.Channel.EnrollScheduleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLStudent.DropEnrolledScheduleResponse web136.SLStudent.ISLStudent.DropEnrolledSchedule(web136.SLStudent.DropEnrolledScheduleRequest request) {
            return base.Channel.DropEnrolledSchedule(request);
        }
        
        public void DropEnrolledSchedule(string student_id, int schedule_id, ref string[] errors) {
            web136.SLStudent.DropEnrolledScheduleRequest inValue = new web136.SLStudent.DropEnrolledScheduleRequest();
            inValue.student_id = student_id;
            inValue.schedule_id = schedule_id;
            inValue.errors = errors;
            web136.SLStudent.DropEnrolledScheduleResponse retVal = ((web136.SLStudent.ISLStudent)(this)).DropEnrolledSchedule(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLStudent.DropEnrolledScheduleResponse> DropEnrolledScheduleAsync(web136.SLStudent.DropEnrolledScheduleRequest request) {
            return base.Channel.DropEnrolledScheduleAsync(request);
        }
    }
}
