//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLScheduleTime {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLScheduleTime.ISLScheduleTime")]
    public interface ISLScheduleTime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/GetScheduleTimeList", ReplyAction="http://tempuri.org/ISLScheduleTime/GetScheduleTimeListResponse")]
        web136.SLScheduleTime.GetScheduleTimeListResponse GetScheduleTimeList(web136.SLScheduleTime.GetScheduleTimeListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/GetScheduleTimeList", ReplyAction="http://tempuri.org/ISLScheduleTime/GetScheduleTimeListResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleTime.GetScheduleTimeListResponse> GetScheduleTimeListAsync(web136.SLScheduleTime.GetScheduleTimeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/InsertScheduleTime", ReplyAction="http://tempuri.org/ISLScheduleTime/InsertScheduleTimeResponse")]
        web136.SLScheduleTime.InsertScheduleTimeResponse InsertScheduleTime(web136.SLScheduleTime.InsertScheduleTimeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/InsertScheduleTime", ReplyAction="http://tempuri.org/ISLScheduleTime/InsertScheduleTimeResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleTime.InsertScheduleTimeResponse> InsertScheduleTimeAsync(web136.SLScheduleTime.InsertScheduleTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/DeleteScheduleTime", ReplyAction="http://tempuri.org/ISLScheduleTime/DeleteScheduleTimeResponse")]
        web136.SLScheduleTime.DeleteScheduleTimeResponse DeleteScheduleTime(web136.SLScheduleTime.DeleteScheduleTimeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLScheduleTime/DeleteScheduleTime", ReplyAction="http://tempuri.org/ISLScheduleTime/DeleteScheduleTimeResponse")]
        System.Threading.Tasks.Task<web136.SLScheduleTime.DeleteScheduleTimeResponse> DeleteScheduleTimeAsync(web136.SLScheduleTime.DeleteScheduleTimeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleTimeList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleTimeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public GetScheduleTimeListRequest() {
        }
        
        public GetScheduleTimeListRequest(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduleTimeListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetScheduleTimeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, string> GetScheduleTimeListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public GetScheduleTimeListResponse() {
        }
        
        public GetScheduleTimeListResponse(System.Collections.Generic.Dictionary<string, string> GetScheduleTimeListResult, string[] errors) {
            this.GetScheduleTimeListResult = GetScheduleTimeListResult;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertScheduleTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public InsertScheduleTimeRequest() {
        }
        
        public InsertScheduleTimeRequest(string time, string[] errors) {
            this.time = time;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertScheduleTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertScheduleTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public InsertScheduleTimeResponse() {
        }
        
        public InsertScheduleTimeResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScheduleTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public DeleteScheduleTimeRequest() {
        }
        
        public DeleteScheduleTimeRequest(int id, string[] errors) {
            this.id = id;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteScheduleTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteScheduleTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] errors;
        
        public DeleteScheduleTimeResponse() {
        }
        
        public DeleteScheduleTimeResponse(string[] errors) {
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLScheduleTimeChannel : web136.SLScheduleTime.ISLScheduleTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLScheduleTimeClient : System.ServiceModel.ClientBase<web136.SLScheduleTime.ISLScheduleTime>, web136.SLScheduleTime.ISLScheduleTime {
        
        public SLScheduleTimeClient() {
        }
        
        public SLScheduleTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLScheduleTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLScheduleTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleTime.GetScheduleTimeListResponse web136.SLScheduleTime.ISLScheduleTime.GetScheduleTimeList(web136.SLScheduleTime.GetScheduleTimeListRequest request) {
            return base.Channel.GetScheduleTimeList(request);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetScheduleTimeList(ref string[] errors) {
            web136.SLScheduleTime.GetScheduleTimeListRequest inValue = new web136.SLScheduleTime.GetScheduleTimeListRequest();
            inValue.errors = errors;
            web136.SLScheduleTime.GetScheduleTimeListResponse retVal = ((web136.SLScheduleTime.ISLScheduleTime)(this)).GetScheduleTimeList(inValue);
            errors = retVal.errors;
            return retVal.GetScheduleTimeListResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleTime.GetScheduleTimeListResponse> GetScheduleTimeListAsync(web136.SLScheduleTime.GetScheduleTimeListRequest request) {
            return base.Channel.GetScheduleTimeListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleTime.InsertScheduleTimeResponse web136.SLScheduleTime.ISLScheduleTime.InsertScheduleTime(web136.SLScheduleTime.InsertScheduleTimeRequest request) {
            return base.Channel.InsertScheduleTime(request);
        }
        
        public void InsertScheduleTime(string time, ref string[] errors) {
            web136.SLScheduleTime.InsertScheduleTimeRequest inValue = new web136.SLScheduleTime.InsertScheduleTimeRequest();
            inValue.time = time;
            inValue.errors = errors;
            web136.SLScheduleTime.InsertScheduleTimeResponse retVal = ((web136.SLScheduleTime.ISLScheduleTime)(this)).InsertScheduleTime(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleTime.InsertScheduleTimeResponse> InsertScheduleTimeAsync(web136.SLScheduleTime.InsertScheduleTimeRequest request) {
            return base.Channel.InsertScheduleTimeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLScheduleTime.DeleteScheduleTimeResponse web136.SLScheduleTime.ISLScheduleTime.DeleteScheduleTime(web136.SLScheduleTime.DeleteScheduleTimeRequest request) {
            return base.Channel.DeleteScheduleTime(request);
        }
        
        public void DeleteScheduleTime(int id, ref string[] errors) {
            web136.SLScheduleTime.DeleteScheduleTimeRequest inValue = new web136.SLScheduleTime.DeleteScheduleTimeRequest();
            inValue.id = id;
            inValue.errors = errors;
            web136.SLScheduleTime.DeleteScheduleTimeResponse retVal = ((web136.SLScheduleTime.ISLScheduleTime)(this)).DeleteScheduleTime(inValue);
            errors = retVal.errors;
        }
        
        public System.Threading.Tasks.Task<web136.SLScheduleTime.DeleteScheduleTimeResponse> DeleteScheduleTimeAsync(web136.SLScheduleTime.DeleteScheduleTimeRequest request) {
            return base.Channel.DeleteScheduleTimeAsync(request);
        }
    }
}
