//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web136.SLAuth {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Logon", Namespace="http://schemas.datacontract.org/2004/07/POCO")]
    [System.SerializableAttribute()]
    public partial class Logon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLAuth.ISLAuth")]
    public interface ISLAuth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLAuth/Authenticate", ReplyAction="http://tempuri.org/ISLAuth/AuthenticateResponse")]
        web136.SLAuth.AuthenticateResponse Authenticate(web136.SLAuth.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISLAuth/Authenticate", ReplyAction="http://tempuri.org/ISLAuth/AuthenticateResponse")]
        System.Threading.Tasks.Task<web136.SLAuth.AuthenticateResponse> AuthenticateAsync(web136.SLAuth.AuthenticateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Authenticate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] errors;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(string email, string password, string[] errors) {
            this.email = email;
            this.password = password;
            this.errors = errors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public web136.SLAuth.Logon AuthenticateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] errors;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(web136.SLAuth.Logon AuthenticateResult, string[] errors) {
            this.AuthenticateResult = AuthenticateResult;
            this.errors = errors;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISLAuthChannel : web136.SLAuth.ISLAuth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SLAuthClient : System.ServiceModel.ClientBase<web136.SLAuth.ISLAuth>, web136.SLAuth.ISLAuth {
        
        public SLAuthClient() {
        }
        
        public SLAuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SLAuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLAuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SLAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web136.SLAuth.AuthenticateResponse web136.SLAuth.ISLAuth.Authenticate(web136.SLAuth.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public web136.SLAuth.Logon Authenticate(string email, string password, ref string[] errors) {
            web136.SLAuth.AuthenticateRequest inValue = new web136.SLAuth.AuthenticateRequest();
            inValue.email = email;
            inValue.password = password;
            inValue.errors = errors;
            web136.SLAuth.AuthenticateResponse retVal = ((web136.SLAuth.ISLAuth)(this)).Authenticate(inValue);
            errors = retVal.errors;
            return retVal.AuthenticateResult;
        }
        
        public System.Threading.Tasks.Task<web136.SLAuth.AuthenticateResponse> AuthenticateAsync(web136.SLAuth.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
    }
}
